# Generated by Django 3.1.6 on 2021-02-04 12:33

from django.db import migrations, models
import pgcrypto.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', pgcrypto.fields.TextDigestField()),
            ],
        ),
    ]
