# Generated by Django 3.1.6 on 2021-02-04 13:01

from django.db import migrations, models
import pgcrypto.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', pgcrypto.fields.TextPGPPublicKeyField()),
                ('email', pgcrypto.fields.EmailPGPSymmetricKeyField(max_length=254)),
            ],
        ),
    ]
